CREATE TABLE EMP (
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR(50) NOT NULL,
    JOB VARCHAR(50),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(10,2),
    COMM NUMBER(10,2),
    DEPTNO NUMBER(2)
);
